{
 "title": "vSphere",
 "description": "A vSphere dashboard based on Prometheus and Telegraf(vSphere input+Prometheu output).",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "${VAR_JOB}" },
   {
    "name": "vcenter",
    "label": "vCenter",
    "query": "label_values(vsphere_host_cpu_usage_average{job=\"$job\"}, vcenter)"
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": "label_values(vsphere_host_cpu_usage_average{job=\"$job\",vcenter=\"$vcenter\"}, dcname)"
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": "label_values(vsphere_host_datastore_read_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\"}, dsname)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(vsphere_host_cpu_usage_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\"}, clustername)"
   },
   {
    "name": "esxi",
    "label": "ESXi",
    "query": "label_values(vsphere_host_cpu_usage_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\"}, esxhostname)"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "label_values(vsphere_host_disk_read_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",esxhostname=~\"$esxi\"}, disk)"
   },
   {
    "name": "nic",
    "label": "NIC",
    "query": "label_values(vsphere_host_net_bytesTx_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",esxhostname=~\"$esxi\"}, interface)"
   },
   {
    "name": "hba",
    "label": "HBA",
    "query": "label_values(vsphere_host_storageAdapter_read_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",esxhostname=~\"$esxi\"}, adapter)"
   },
   {
    "name": "vm",
    "label": "VM",
    "query": "label_values(vsphere_vm_cpu_usage_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",esxhostname=~\"$esxi\"}, vmname)"
   }
  ]
 },
 "panels": [
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "content": "\n# About This Dashboard\n\nThis dashboard is the basedashboard for vSphere which covers performance for below objects:\n\n- vSphere ESXi\n- vSphere VM\n- vSphere Datastore\n\nUsers should **pick panels based on their own requirements**.\n\n# Prometheus Exporter\n\nMetrics are colleced by leveraging [telegraf](https://www.influxdata.com/time-series-platform/telegraf/) from Influxdata. A skeleton configuration file can be generated as below:\n\n```bash\n telegraf --section-filter agent:inputs:outputs --input-filter vsphere --output-filter prometheus_client config > telegraf.conf\n```\n\n# Reference\n\n- [Telegraf vSphere Input Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/vsphere)\n- [vSphere Performance Counter Reference](https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/vim.PerformanceManager.html)\n- [How to convert vSphere summation counters](https://kb.vmware.com/s/article/2002181)\n- [Sample configurations](https://github.com/kckecheng/prometheus/tree/master/config/telegraf_vsphere)\n"
  },
  {
   "title": "Host CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Avg Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_cpu_usage_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",cpu=\"instance-total\"}",
       "legendFormat": "{{ esxhostname }}"
      }
     ]
    },
    {
     "title": "CPU Latency",
     "type": "graph",
     "description": "Percent of time the virtual machine is unable to run because it is contending for access to the physical CPU(s)",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_cpu_latency_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",cpu=\"instance-total\",esxhostname=~\"$esxi\"}",
       "legendFormat": "{{ esxhostname }}"
      }
     ]
    },
    {
     "title": "CPU Readiness",
     "type": "graph",
     "description": "Percentage of time that the virtual machine was ready, but could not get scheduled to run on the physical CPU.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_cpu_readiness_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",cpu=\"instance-total\",esxhostname=~\"$esxi\"}",
       "legendFormat": "{{ esxhostname }}"
      }
     ]
    },
    {
     "title": "CPU Wait",
     "type": "graph",
     "description": "Total CPU time spent in wait state.The wait total includes time spent the CPU Idle, CPU Swap Wait, and CPU I/O Wait states.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_cpu_wait_summation{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",cpu=\"instance-total\",esxhostname=~\"$esxi\"} / 200",
       "legendFormat": "{{ esxhostname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Avg Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_mem_usage_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\"}",
       "legendFormat": "{{ esxhostname }}"
      }
     ]
    },
    {
     "title": "Memory Swap In/Out Rate",
     "type": "graph",
     "description": "https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/memory_counters.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_mem_swapinRate_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\"}",
       "legendFormat": "{{ esxhostname }} In"
      },
      {
       "expr": "vsphere_host_mem_swapoutRate_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\"}",
       "legendFormat": "{{ esxhostname }} Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_net_bytesRx_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",interface=~\"$nic\"}",
       "legendFormat": "{{ esxhostname }}/{{  interface }} Rx"
      },
      {
       "expr": "vsphere_host_net_bytesTx_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",interface=~\"$nic\"}",
       "legendFormat": "{{ esxhostname }}/{{  interface }} Tx"
      }
     ]
    },
    {
     "title": "Network Package",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_net_packetsRx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",interface=~\"$nic\"} / 200",
       "legendFormat": "{{ esxhostname }}/{{  interface }} Rx"
      },
      {
       "expr": "vsphere_host_net_packetsTx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",interface=~\"$nic\"} / 200",
       "legendFormat": "{{ esxhostname }}/{{  interface }} Tx"
      }
     ]
    },
    {
     "title": "Network Dropped",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_net_droppedRx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",interface=~\"$nic\"} / 200",
       "legendFormat": "{{ esxhostname }}/{{  interface }} Rx"
      },
      {
       "expr": "vsphere_host_net_droppedTx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",interface=~\"$nic\"} / 200",
       "legendFormat": "{{ esxhostname }}/{{  interface }} Tx"
      }
     ]
    },
    {
     "title": "Network Error",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_net_errorsRx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",interface=~\"$nic\"} / 200",
       "legendFormat": "{{ esxhostname }}/{{  interface }}  Rx"
      },
      {
       "expr": "vsphere_host_net_errorsTx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",interface=~\"$nic\"} / 200",
       "legendFormat": "{{ esxhostname }}/{{  interface }} Tx"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_disk_read_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",disk=~\"$disk\"}",
       "legendFormat": "{{ esxhostname }}/{{  disk }} R"
      },
      {
       "expr": "vsphere_host_disk_write_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",disk=~\"$disk\"}",
       "legendFormat": "{{ esxhostname }}/{{  disk }} W"
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_disk_numberReadAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",disk=~\"$disk\"}",
       "legendFormat": "{{ esxhostname }}/{{  disk }} R"
      },
      {
       "expr": "vsphere_host_disk_numberWriteAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",disk=~\"$disk\"}",
       "legendFormat": "{{ esxhostname }}/{{  disk }} W"
      }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_disk_totalReadLatency_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",disk=~\"$disk\"}",
       "legendFormat": "{{ esxhostname }}/{{  disk }} R"
      },
      {
       "expr": "vsphere_host_disk_totalWriteLatency_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",disk=~\"$disk\"}",
       "legendFormat": "{{ esxhostname }}/{{  disk }} W"
      }
     ]
    },
    {
     "title": "Disk Commands",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_disk_commandsAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",disk=~\"$disk\"}",
       "legendFormat": "{{ esxhostname }}/{{  disk }}"
      }
     ]
    },
    {
     "title": "Disk Command Aborted",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_disk_commandsAborted_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",disk=~\"$disk\"}/ 200",
       "legendFormat": "{{ esxhostname }}/{{  disk }}"
      }
     ]
    },
    {
     "title": "Disk Max Total Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_disk_maxTotalLatency_latest{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",disk=\"instance-total\"}",
       "legendFormat": "{{ esxhostname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host HBA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "HBA Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_storageAdapter_read_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",adapter=~\"$hba\"}",
       "legendFormat": "{{ esxhostname }}/{{  adapter }} R"
      },
      {
       "expr": "vsphere_host_storageAdapter_write_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",adapter=~\"$hba\"}",
       "legendFormat": "{{ esxhostname }}/{{ adapter }} W"
      }
     ]
    },
    {
     "title": "HBA IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_storageAdapter_numberReadAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",adapter=~\"$hba\"}",
       "legendFormat": "{{ esxhostname }}/{{  adapter }} R"
      },
      {
       "expr": "vsphere_host_storageAdapter_numberWriteAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",adapter=~\"$hba\"}",
       "legendFormat": "{{ esxhostname }}/{{ adapter }} W"
      }
     ]
    },
    {
     "title": "HBA Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_storageAdapter_totalReadLatency_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",adapter=~\"$hba\"}",
       "legendFormat": "{{ esxhostname }}/{{  adapter }} R"
      },
      {
       "expr": "vsphere_host_storageAdapter_totalWriteLatency_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",adapter=~\"$hba\"}",
       "legendFormat": "{{ esxhostname }}/{{ adapter }} W"
      }
     ]
    },
    {
     "title": "HBA Queued I/O",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vsphere_host_storageAdapter_queued_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",adapter=~\"$hba\"}",
       "legendFormat": "{{ esxhostname }}/{{  adapter }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Datastore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Datastore Throughput(Host View)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "sum by(dsname) (vsphere_host_datastore_read_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
       "legendFormat": "{{ dsname }} R"
      },
      {
       "expr": "sum by(dsname) (vsphere_host_datastore_read_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
       "legendFormat": "{{ dsname }} W"
      }
     ]
    },
    {
     "title": "Datastore IOPS(Host View)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum by(dsname) (vsphere_host_datastore_numberReadAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
       "legendFormat": "{{ dsname }} R"
      },
      {
       "expr": "sum by(dsname) (vsphere_host_datastore_numberWriteAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
       "legendFormat": "{{ dsname }} W"
      }
     ]
    },
    {
     "title": "Datastore Max Latency(Host View)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "max by(dsname) (vsphere_host_datastore_totalReadLatency_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
       "legendFormat": "{{ dsname }} R"
      },
      {
       "expr": "max by(dsname) (vsphere_host_datastore_totalReadLatency_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
       "legendFormat": "{{ dsname }} W"
      }
     ]
    },
    {
     "title": "Datastore Throughput(VM View)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "sum by(dsname) (vsphere_vm_datastore_read_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
       "legendFormat": "{{ dsname }} R"
      },
      {
       "expr": "sum by(dsname) (vsphere_vm_datastore_read_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
       "legendFormat": "{{ dsname }} W"
      }
     ]
    },
    {
     "title": "Datastore IOPS(VM View)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum by(dsname) (vsphere_vm_datastore_numberReadAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
       "legendFormat": "{{ dsname }} R"
      },
      {
       "expr": "sum by(dsname) (vsphere_vm_datastore_numberWriteAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
       "legendFormat": "{{ dsname }} W"
      }
     ]
    },
    {
     "title": "Datastore Max Latency(VM View)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "max by(dsname) (vsphere_vm_datastore_totalReadLatency_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
       "legendFormat": "{{ dsname }} R"
      },
      {
       "expr": "max by(dsname) (vsphere_vm_datastore_totalReadLatency_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
       "legendFormat": "{{ dsname }} W"
      }
     ]
    }
   ]
  },
  {
   "title": "VM CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "vsphere_vm_cpu_usage_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"}",
       "legendFormat": "{{ esxhostname }}/{{ vmname }}"
      }
     ]
    },
    {
     "title": "CPU Latency",
     "type": "graph",
     "description": "Percent of time the virtual machine is unable to run because it is contending for access to the physical CPU(s)",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "vsphere_vm_cpu_latency_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",cpu=\"instance-total\",esxhostname=~\"$esxi\",vmname=~\"$vm\"}",
       "legendFormat": "{{ esxhostname }}/{{ vmname }}"
      }
     ]
    },
    {
     "title": "CPU Readiness",
     "type": "graph",
     "description": "Percentage of time that the virtual machine was ready, but could not get scheduled to run on the physical CPU.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "vsphere_vm_cpu_readiness_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",cpu=\"instance-total\",esxhostname=~\"$esxi\",vmname=~\"$vm\"}",
       "legendFormat": "{{ esxhostname }}/{{ vmname }}"
      }
     ]
    },
    {
     "title": "CPU Wait",
     "type": "graph",
     "description": "Total CPU time spent in wait state.The wait total includes time spent the CPU Idle, CPU Swap Wait, and CPU I/O Wait states.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "vsphere_vm_cpu_wait_summation{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",cpu=\"instance-total\",esxhostname=~\"$esxi\",vmname=~\"$vm\"} / 200",
       "legendFormat": "{{ esxhostname }}/{{ vmname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "VM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Avg Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "vsphere_vm_mem_usage_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"}",
       "legendFormat": "{{ esxhostname }}/{{ vmname }}"
      }
     ]
    },
    {
     "title": "Memory Swap In/Out Rate",
     "type": "graph",
     "description": "https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/memory_counters.html",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "vsphere_vm_mem_swapinRate_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"}",
       "legendFormat": "{{ esxhostname }}/{{ vmname}} In"
      },
      {
       "expr": "vsphere_vm_mem_swapoutRate_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"}",
       "legendFormat": "{{ esxhostname }}/{{ vmname }} Out"
      }
     ]
    }
   ]
  },
  {
   "title": "VM Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "vsphere_vm_net_bytesRx_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\",interface=\"instance-total\"}",
       "legendFormat": "{{ esxhostname }}/{{ vmname }} Rx"
      },
      {
       "expr": "vsphere_vm_net_bytesTx_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\",interface=\"instance-total\"}",
       "legendFormat": "{{ esxhostname }}/{{  vmname }} Tx"
      }
     ]
    },
    {
     "title": "Network Package",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "vsphere_vm_net_packetsRx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\",interface=\"instance-total\"} / 200",
       "legendFormat": "{{ esxhostname }}/{{ vmname }} Rx"
      },
      {
       "expr": "vsphere_vm_net_packetsTx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\",interface=\"instance-total\"} / 200",
       "legendFormat": "{{ esxhostname }}/{{  vmname }} Tx"
      }
     ]
    },
    {
     "title": "Network Dropped",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "vsphere_vm_net_droppedRx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\",interface=\"instance-total\"} / 200",
       "legendFormat": "{{ esxhostname }}/{{  vmname }} Rx"
      },
      {
       "expr": "vsphere_vm_net_droppedTx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\",interface=\"instance-total\"} / 200",
       "legendFormat": "{{ esxhostname }}/{{  vmname }} Tx"
      }
     ]
    }
   ]
  },
  {
   "title": "VM Virtual Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "vsphere_vm_virtualDisk_read_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\",disk=\"instance-total\"}",
       "legendFormat": "{{ esxhostname }}/{{  vmname }} R"
      },
      {
       "expr": "vsphere_vm_virtualDisk_write_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\",disk=\"instance-total\"}",
       "legendFormat": "{{ esxhostname }}/{{ vmname }} W"
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum without(disk) (vsphere_vm_virtualDisk_numberReadAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"})",
       "legendFormat": "{{ esxhostname }}/{{  vmname }} R"
      },
      {
       "expr": "sum without(disk) (vsphere_vm_virtualDisk_numberWriteAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"})",
       "legendFormat": "{{ esxhostname }}/{{  vmname }} W"
      }
     ]
    },
    {
     "title": "Disk Outstanding Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum without(disk) (vsphere_vm_virtualDisk_readOIO_latest{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"})",
       "legendFormat": "{{ esxhostname }}/{{  vmname }} R"
      },
      {
       "expr": "sum without(disk) (vsphere_vm_virtualDisk_writeOIO_latest{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"})",
       "legendFormat": "{{ esxhostname }}/{{  vmname }} W"
      }
     ]
    },
    {
     "title": "Disk Max Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max without(disk) (vsphere_vm_virtualDisk_totalReadLatency_average{vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"})",
       "legendFormat": "{{ esxhostname }}/{{ vmname }} R"
      },
      {
       "expr": "max without(disk) (vsphere_vm_virtualDisk_totalWriteLatency_average{vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"})",
       "legendFormat": "{{ esxhostname }}/{{ vmname }} W"
      }
     ]
    }
   ]
  }
 ]
}