global:
  scrape_interval: 15s

scrape_configs:
  # Job 1: Memonitor Prometheus itu sendiri (best practice)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Job 2: Monitor OS Target Host Ubuntu
  - job_name: 'target_server_1' # Beri nama yang deskriptif
    static_configs:
      - targets: ['10.78.108.41:9100']

  # Job 3: Monitor FTM Esxi Host Server
  - job_name: 'telegraf-vsphere'
    scrape_interval: 60s
    static_configs:
      - targets: ['telegraf:9273']



#  - job_name: 'grafana-agent-vsphere'
#    scrape_interval: 60s
#    static_configs:
#      - targets: ['grafana-agent:12345']


#  - job_name: 'vsphere-esxi'
#    scrape_interval: 60s
#    static_configs:
#      - targets: ['vsphere-exporter:9272']
